name: "collector-pivotal-tracker"
version: "0.0.1"
description: "Collector for Pivotal Tracker activity web hook"
dependencies:
  - name: "abstract-webhook"
    url: "git+ssh://git@github.com/salsita-cider/cider-abstract-webhook"
